[tox]
envlist =
    py{310,311,312}
    py{310,311,312}-{poppydev,pysiafdev,astropydev}
    py310-legacy
    py{310,311,312}-{poppydev,pysiafdev}-cov
    py311-docbuild

isolated_build = true

[testenv]
passenv = *
extras =
    test
deps = 
    poppydev,astropydev: git+https://github.com/spacetelescope/poppy.git#egg=poppy
    pysiafdev,astropydev: git+https://github.com/spacetelescope/pysiaf.git#egg=pysiaf
    astropydev: astropy>=0.0.dev0
    poppydev: synphot
    cov: pytest-cov
    xdist: pytest-xdist
uv_resolution =
    legacy: lowest-direct
    !legacy: highest
commands=
    pytest \
    cov: --cov-config=pyproject.toml --cov-report=xml --cov=stpsf 
    xdist: -n=2 --dist=loadscope \
    {posargs}

[testenv:docbuild]
passenv= *
extras =
    docs
commands=
    sphinx-build docs docs/_build

[testenv:codestyle]
skip_install = true
description = check package code style
deps =
    pycodestyle
commands =
    pycodestyle stpsf

[testenv:flake8]
exclude= .git,__pycache__, test*
max-line-length = 120
