# retrieves the latest cache key for STPSF data;
# the cache key is in the form `stpsf-data-mini-1.3.0`,
# `stpsf-data-full-1.3.0`, `stpsf-data-prerel-1.3.1` etc.
#
# to retrieve the STPSF data cache in your test workflow,
# first create a cache of the dataset in your repository
# (see `download_data.yml` for instructions), then
# call this workflow as a needed job and use `actions/cache/restore`
# to place the data in your test job:
#
# # .github/workflows/tests.yml
# name: run tests
# ...
# jobs:
#   stpsf_data_cache_key:
#     uses: spacetelescope/stpsf/.github/workflows/retrieve_cache.yml@beda656c80a0254e6f80649d9c9c49235634522f  # v1.4.0
#     with:
#       minimal: true
#   tests:
#     needs: [ stpsf_data_cache_key ]
#     steps:
#       ...
#       - name: retrieve STPSF data cache
#        uses: actions/cache/restore@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9  # v4.0.2
#        with:
#          path: ${{ runner.temp }}/stpsf-data
#          key: ${{ needs.stpsf_data_cache_key.outputs.cache_key }}
#       ...

name: retrieve cache

on:
  workflow_call:
    inputs:
      dataset_type:
        description: "Choose dataset type ('development' or 'latest_release')"
        type: string
        required: false
        default: development
    outputs:
      cache_path:
        value: ${{ jobs.retrieve.outputs.cache_path }}
      cache_key:
        value: ${{ jobs.retrieve.outputs.cache_key }}
      version:
        value: ${{ jobs.retrieve.outputs.version }}

jobs:
  retrieve:
    runs-on: ubuntu-latest
    steps:
      - name: Determine cache key
        id: cache-key
        run: |
          PREFIX="stpsf-data-${{ inputs.dataset_type }}-"

          # use actions/gh-actions-cache to allow filtering by key
          gh extension install actions/gh-actions-cache

          # Find the most recent cache key matching dataset type
          CACHE_KEY=$(gh actions-cache list -R ${{ github.repository }} --key "$PREFIX" --sort created-at | cut -f1 | head -n1)

          echo "cache_key=$CACHE_KEY" >> $GITHUB_OUTPUT

          # Extract version (suffix after prefix, if present)
          VERSION=${CACHE_KEY#"$PREFIX"}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

          # Path where cache would be restored
          echo "cache_path=/tmp/stpsf-cache/$CACHE_KEY" >> $GITHUB_OUTPUT

      - name: Set outputs
        id: set-outputs
        run: |
          echo "cache_key=${{ steps.cache-key.outputs.cache_key }}" >> $GITHUB_OUTPUT
          echo "version=${{ steps.cache-key.outputs.version }}" >> $GITHUB_OUTPUT
          echo "cache_path=${{ steps.cache-key.outputs.cache_path }}" >> $GITHUB_OUTPUT

    outputs:
      cache_path: ${{ steps.set-outputs.outputs.cache_path }}
      cache_key: ${{ steps.set-outputs.outputs.cache_key }}
      version: ${{ steps.set-outputs.outputs.version }}
